name = "CircModDesign"
uuid = "19f57439-1cb0-4d36-9335-a15a76ba1aac"
authors = ["Eli Mattingly"]
version = "0.1.0"

[deps]
ACME = "ca8b7239-ccd3-5cce-807f-2072f3f0d108"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ElectricalEngineering = "84e62fa8-74a0-5990-9214-c45bd74ae4d7"
Elliptic = "b305315f-e792-5b7a-8f41-49f472929428"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI_Tools = "97d903a3-cacc-4b79-8a19-43190c4af4ff"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Struve = "bbbc800e-c7bf-11e8-107b-9b6d1d23829a"

[compat]
DataFrames = "1"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
